import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header title='Bitbit' />
      <p className='text-xl sm:text-5xl font-bold center'>
        어려운 <span style={{ color: '#f6931a' }}>암호화폐</span>. <br />
        <span className='inline text-blue-500'>모의투자</span>로 시작하다.
      </p>
    </div>
  )
}

export default Home
