import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBitcoin } from '@fortawesome/free-brands-svg-icons'
import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <p className='text-5xl font-bold center'>
        어려운 <p className='inline' style={{ color: '#f6931a' }}>비트코인</p>. <br />
        <p className='inline text-blue-500'>모의투자</p>로 시작하다.
      </p>
    </div>
  )
}

export default Home
