import type { NextPage } from 'next'
import Head from 'next/head'
import Currency from '../components/Currency'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faDollarSign, faWonSign } from '@fortawesome/free-solid-svg-icons'
import { faBitcoin, faEthereum } from '@fortawesome/free-brands-svg-icons'

import Header from '../components/Header'

const Wallet: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bitbit - Wallet</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header title='Bitbit/Wallet' />

      <div className='px-6'>
        <p className='font-bold text-3xl'>Fiats</p> <br />
        <div className='flex gap-3 flex-col'>
          <Currency name='KRW' icon={<FontAwesomeIcon icon={faWonSign}/>} moneyText='₩100,000,000' />
          <Currency name='USD' icon={<FontAwesomeIcon icon={faDollarSign}/>} moneyText='$10,000' />
        </div>
        <br />
        <p className='font-bold text-3xl'>Crypto Currencies</p> <br />
        <div className='flex gap-3 flex-col'>
          <Currency name='Bitcoin' icon={<FontAwesomeIcon icon={faBitcoin}/>} moneyText='1.201 BTC' />
          <Currency name='Ethereum' icon={<FontAwesomeIcon icon={faEthereum}/>} moneyText='2.56 ETH' />
        </div>
      </div>
    </div>
  )
}

export default Wallet
